@startuml
| Unity Event Functions |
:Start;
    |#lightgray| YVR Core Functions |
    :Init Native Plugin;
        | Native Functions |
        : YVRInitialize;
    | YVR Core Functions |
    :Apply Tracking Mode Settings;
        | Native Functions |
        : SetUsingIPDInPositionTracking;
        : YVRSetUsingIPDInPositionTracking;
        : YVRSetTracking;
    | YVR Core Functions |
    :Apply Performance Settings;
        | Native Functions |
        : YVRSetCPULevel;
        : YVRSetGPULevel;
    | YVR Core Functions |
    :Begin VR Mode;
        | Native Functions |
        : IssueDataEvent(BeginVREvent);
    | YVR Core Functions |
    :Init Camera Rig;
    :Init Controller Rig;
    :Init Camera Renderer;
        | Native Functions |
        : YVRGetEyeResolution;
        : YVRGetEyeFov;
    | YVR Core Functions |
    :Init Layer Manager;
repeat
    | Unity Event Functions |
    :Update;
        | YVR Core Functions |
        : Input Update;
            | Native Functions |
            : YVRGetControllerConnected;
            : YVRGetControllerState;
        | YVR Core Functions |
        :onUpdate;
        partition "onUpdate" {
            : Update Overlay Vertices;
            : Update Laser Beam;
        }
        :onTrackingAcquired;
        :onTrackingLost;
            | Native Functions |
            : YVRIsUserPresent;
        | YVR Core Functions |
        :onHMDMounted;
        :onHMDUnMounted;
        :Add Frame Count;
    | Unity Event Functions |
    : yield WaitUntil;
        | Native Functions |
        : SvrIsRunning;
        | YVR Core Functions |
        partition "VRMode Began" {
            : OnVRModeBegan;
            :Apply Rendering Quality Settings;
                | Native Functions |
                : IssueDataEvent(SetFoveationDataEvent);
        }
    | Unity Event Functions |
    : LateUpdate ;
        | YVR Core Functions |
        : onLateUpdate;
        partition "onLateUpdate" {
            : Update Head Pose;
                | Native Functions |
                : YVRGetTrackingData;
            | YVR Core Functions |
            : Update Controller Pose;
                | Native Functions |
                : YVRGetTrackingData;
        }
    | Unity Event Functions |
    :OnPreRender;
        | YVR Core Functions |
        : Swap Eye Buffers;
        : BeginEye;
            | Native Functions |
            : IssueDataEvent(BeginEyeEvent);
    | Unity Event Functions |
    : OnPostRender;
        | YVR Core Functions |
        : End Eye;
            | Native Functions |
            : IssueDataEvent(EndEyeEvent);
    | Unity Event Functions |
    : yield WaitForEndOfFrame;
        | YVR Core Functions |
        : Submit Frame;
            | Native Functions |
            : IssueDataEvent(SubmitFrameEvent);
    | Unity Event Functions |
    : OnApplicationPause;
        if (IsPause?) then (yes)
            | YVR Core Functions |
            : End VR Mode;
                | Native Functions |
                : IssueDataEvent(BeginVREvent);
        else (no)
            | YVR Core Functions |
            : Begin VR Mode;
                | Native Functions |
                : IssueDataEvent(EndVREvent);
        endif
repeat while(Application Quit) is (No)

| Unity Event Functions |
: OnApplicationQuit;
    | YVR Core Functions |
    : Shut Down;
        | Native Functions |
        : YVRShutDown;
@enduml