using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace YVR.Utilities
{
    /// <summary>
    /// Base class for all log prefix
    /// </summary>
    public abstract class LogPrefixBase
    {
        private LogPrefixBase wrappedLogPrefix = null;

        /// <summary>
        /// Constructor for log prefix
        /// </summary>
        /// <param name="wrappedLogPrefix"> The wrapped log prefix </param>
        public LogPrefixBase(LogPrefixBase wrappedLogPrefix = null)
        {
            this.wrappedLogPrefix = wrappedLogPrefix;
        }

        /// <summary>
        /// Get prefix which combined wrapped log prefix result and current log prefix result
        /// </summary>
        /// <param name="context"> The context where output the log </param>
        /// <param name="log"> The log message </param>
        /// <param name="priority"> Log Priority </param>
        /// <returns> Combined prefix result </returns>
        public virtual string GetCombinedPrefix(in object context, in string log, in LogPriority priority)
        {
            return $"{wrappedLogPrefix?.GetPrefix(context, log, priority) ?? string.Empty} {GetPrefix(in context, in log, in priority)}";
        }

        /// <summary>
        /// Function to get prefix
        /// </summary>
        /// <param name="context"> The context where output the log </param>
        /// <param name="log"> The log message </param>
        /// <param name="priority"> Log Priority </param>
        /// <returns>The result generated by this prefix</returns>
        public abstract string GetPrefix(in object context, in string log, in LogPriority priority);
    }
}